ll: informe

informe: 
	xelatex informe.tex
	xelatex informe.tex

p: 
	xelatex informe.tex
	xelatex informe.tex
	zathura informe.pdf

r: 
	xelatex informe.tex
	xelatex informe.tex
	evince informe.pdf &

clean:
	rm -rf *.aux *.toc *.log *.out *.lof *.lot

